---
- name: Download do Wordpress .tar
  get_url:
    url: https://br.wordpress.org/latest-pt_BR.tar.gz
    dest: /tmp/wordpress.tar.gz
  become: true

- name: Descompactar o Wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: true
  become: true

- name: Modificando arquivo de exemplo para instalação do Wordpress
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: true
  become: true

- name: alterando arquivo config para comunicação com o DB
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  loop:
    - {regex: 'nome_do_banco_de_dados_aqui', value: "{{ wp_db_name }}"}
    - {regex: 'nome_de_usuario_aqui', value: "{{ wp_db_user }}"}
    - {regex: 'senha_aqui', value: "{{ wp_db_user_password }}"}
    - { regex: 'localhost', value: "{{ wp_db_ip }}"}
  become: true

- name: Configurando Apache para buscar o index na pasta do Wordpress
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: true
  notify:
    - restart Apache