---
- name: Instalando MySQL server
  apt: name=mysql-server state=present
  become: true

- name: Instalando módulos MySQL
  apt:
    name:
      - python3-mysqldb
      - python3-dev
      - default-libmysqlclient-dev
      - build-essential
    state: present
    update_cache: yes
  become: true

- name: Criando banco de dados para o WordPress
  mysql_db:
    name: "{{ wp_db_name }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present 
  become: yes

- name: Criando usuário do MySQL
  mysql_user:
    login_user: root
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  loop:
    - 'localhost'
    - '127.0.0.1'
    - '{{ wp_host_ip }}'
  become: true

- name: Alterando arquivo mysqld.cnf para aceitar acesso remoto
  copy:
    src: 'files/mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
  become: true
  notify:
    - restart mysql
